name: Run ip.py script

on: 
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Update pip
      run: |
        pip install --upgrade pip
    - name: Install dependencies
      run: | 
        pip install requests output_files
    - name: Run ip.py script
      run: |
        python ip.py
